// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdyEtUZyb6ll7-npm4r4iqtvzwslzFgLM',
    appId: '1:977701026567:web:1f21c6eae9920892c3a3a2',
    messagingSenderId: '977701026567',
    projectId: 'userblogger',
    authDomain: 'userblogger.firebaseapp.com',
    storageBucket: 'userblogger.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe4fFrWR3An9Tg6rejfFThzrWsJCHdnrc',
    appId: '1:977701026567:android:a14497cdfa0362c3c3a3a2',
    messagingSenderId: '977701026567',
    projectId: 'userblogger',
    storageBucket: 'userblogger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiUkZdrPUf7UXb-GG1rV5PC0NqUiCU1hQ',
    appId: '1:977701026567:ios:6f9c854040d90661c3a3a2',
    messagingSenderId: '977701026567',
    projectId: 'userblogger',
    storageBucket: 'userblogger.appspot.com',
    iosBundleId: 'com.chihozhwa.userblogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiUkZdrPUf7UXb-GG1rV5PC0NqUiCU1hQ',
    appId: '1:977701026567:ios:6f9c854040d90661c3a3a2',
    messagingSenderId: '977701026567',
    projectId: 'userblogger',
    storageBucket: 'userblogger.appspot.com',
    iosBundleId: 'com.chihozhwa.userblogger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdyEtUZyb6ll7-npm4r4iqtvzwslzFgLM',
    appId: '1:977701026567:web:a0c50b1f08f99aefc3a3a2',
    messagingSenderId: '977701026567',
    projectId: 'userblogger',
    authDomain: 'userblogger.firebaseapp.com',
    storageBucket: 'userblogger.appspot.com',
  );
}
